services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.24
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es01-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
    mem_limit: 512m
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.24
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601
    depends_on:
      - es01
    networks:
      - esnet
    mem_limit: 256m
    restart: always

  web:
    image: yobubble62/doraemon_gadgets_search_engine:amd64
    container_name: doraemon
    environment:
      - ELS_HOST=http://es01:9200
    ports:
      - 3000:3000
    depends_on:
      - es01
    networks:
      - esnet
    mem_limit: 256m # Enforce memory limit for the web service
    restart: always

networks:
  esnet:
